# Rice — theme in theme.conf (no Tokyo Night)
include theme.conf

font_family     JetBrains Mono Nerd Font
bold_font       auto
italic_font     auto
bold_italic_font auto
font_size       12
url_style       dotted
window_padding_width 15

tab_bar_min_tabs 2
tab_bar_style powerline
tab_powerline_style slanted
tab_title_template {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}

map kitty_mod+enter launch --cwd=current --type=window
map cmd+enter       launch --cwd=current --type=window
map kitty_mod+t     launch --cwd=current --type=tab
map cmd+t           launch --cwd=current --type=tab

cursor_shape beam
cursor_shape_unfocused hollow
enable_audio_bell no

tab_bar_style fade
tab_fade 1
active_tab_font_style   bold
inactive_tab_font_style bold
map ctrl+t launch --cwd=current --type=tab
